# Book settings
title: Laplx's Blog
author: Laplx (Hao Chen)
logo: 'logo.png'

html:
  favicon: favicon.ico
  google_analytics_id: G-PPZXJ9B1BG

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    language: English
